@CJSV = 
  line: () ->
    _outstream=""

    _oustream += "<div id=\"por-que\">"
    _oustream += "  <p>Alface"
    _oustream += "  </p>"
    _oustream += "  <p>Queijo"
    _oustream += "    <label>Alface"
    _oustream += "    </label>"
    _oustream += "  </p>"
    _oustream += "  <div id=\"p\">"
    _oustream += "    <a>"
    _oustream += "      <span>"
    _oustream += "      </span>"
    _oustream += "    </a>"
    _oustream += "    <p>"
    _oustream += "    </p>"
    _oustream += "  </div>"
    _oustream += "</div>"
